# Generated by Django 2.2 on 2019-04-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockingevent',
            name='mark',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Chemical, tag, or finclip mark applied to fish'),
        ),
    ]
