# Generated by Django 2.2 on 2019-09-06 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocking', '0002_auto_20190906_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='datauploadevent',
            name='slug',
            field=models.CharField(default='foobar', max_length=75, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datauploadevent',
            name='agency',
            field=models.ForeignKey(default='USFWS', on_delete=django.db.models.deletion.CASCADE, related_name='upload_events', to='common.Agency', to_field='abbrev'),
        ),
        migrations.AlterField(
            model_name='datauploadevent',
            name='lake',
            field=models.ForeignKey(default='HU', on_delete=django.db.models.deletion.CASCADE, related_name='upload_events', to='common.Lake', to_field='abbrev'),
        ),
    ]
