# Generated by Django 2.2 on 2019-04-19 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20190419_0057'),
        ('stocking', '0002_auto_20190415_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockingevent',
            name='management_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stocking_events', to='common.ManagementUnit'),
            preserve_default=False,
        ),
    ]
