# Generated by Django 2.1.4 on 2019-01-09 17:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocking', '0002_stockingevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockingevent',
            name='yreq_stocked',
            field=models.IntegerField(default=0, verbose_name='Number of fish stocked as yearling equivalents'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockingevent',
            name='agemonth',
            field=models.IntegerField(blank=True, null=True, verbose_name='age of stocked fish in months'),
        ),
        migrations.AlterField(
            model_name='stockingevent',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Stocking event date'),
        ),
        migrations.AlterField(
            model_name='stockingevent',
            name='day',
            field=models.IntegerField(blank=True, null=True, verbose_name='Day of the month'),
        ),
        migrations.AlterField(
            model_name='stockingevent',
            name='dd_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude in decimal degrees'),
        ),
        migrations.AlterField(
            model_name='stockingevent',
            name='dd_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude in decimal degrees'),
        ),
        migrations.AlterField(
            model_name='stockingevent',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='GeoDjango spatial point field'),
        ),
        migrations.AlterField(
            model_name='stockingevent',
            name='length',
            field=models.IntegerField(blank=True, null=True, verbose_name='length of stocked fish in mm'),
        ),
        migrations.AlterField(
            model_name='stockingevent',
            name='lotcode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hatchery Lot code indicating source of stocked fish'),
        ),
        migrations.AlterField(
            model_name='stockingevent',
            name='mark',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='Chemical, tag, or finclip mark applied to fish'),
        ),
        migrations.AlterField(
            model_name='stockingevent',
            name='mark_eff',
            field=models.FloatField(blank=True, null=True, verbose_name='Marking efficency as a percentage'),
        ),
        migrations.AlterField(
            model_name='stockingevent',
            name='month',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Month of stokcing event as an integer'),
        ),
        migrations.AlterField(
            model_name='stockingevent',
            name='no_stocked',
            field=models.IntegerField(verbose_name='Number of fish stocked'),
        ),
        migrations.AlterField(
            model_name='stockingevent',
            name='tag_ret',
            field=models.FloatField(blank=True, null=True, verbose_name='Tag retention as a percentage'),
        ),
        migrations.AlterField(
            model_name='stockingevent',
            name='validation',
            field=models.IntegerField(blank=True, choices=[(0, 'level 0, entered at hatchery, unknown verification status'), (1, 'level 1, entered at hatchery and not verified'), (2, 'level 2, entered and verified at hatchery'), (3, 'level 3, entered at hatchery and verified by GBFRO'), (4, 'level 4, entered and verified at hatchery and verified at GBFRO'), (5, 'level 5, entered and verified at GLFC'), (6, 'level 6, entered and verified at GBFRO'), (7, 'entered by Dept. FW, MSU., not avail. from GLFC'), (8, 'entered by COTFMA'), (9, 'assumed to be validated by state prior to receipt'), (10, 'level 10, data entered and verified at OMNR')], null=True, verbose_name='Event Data Validation Code 0-10.'),
        ),
        migrations.AlterField(
            model_name='stockingevent',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='weight of stocked fish in grams'),
        ),
        migrations.AlterField(
            model_name='stockingevent',
            name='year',
            field=models.IntegerField(db_index=True, verbose_name='year of the stocking event as an integer >1900'),
        ),
        migrations.AlterField(
            model_name='stockingevent',
            name='year_class',
            field=models.IntegerField(db_index=True, verbose_name='Year class of stocked fish'),
        ),
    ]
