# Generated by Django 2.2 on 2020-05-05 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_managementunit_grid10s'),
        ('stocking', '0003_auto_20190906_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockingevent',
            name='agency_stock_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Hatchery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hatchery_name', models.CharField(max_length=250, unique=True)),
                ('abbrev', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('hatchery_type', models.CharField(blank=True, choices=[('private', 'Private'), ('state', 'State'), ('provincial', 'Provincial'), ('federal', 'Federal'), ('other', 'Other')], max_length=25, null=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hatcheries', to='common.Agency')),
            ],
        ),
    ]
