# Generated by Django 2.1.4 on 2019-01-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocking', '0003_auto_20190109_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockingmethod',
            name='stk_meth',
            field=models.CharField(max_length=25, unique=True, verbose_name='Stocking Method'),
        ),
    ]
