# Generated by Django 2.1.4 on 2019-02-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocking', '0004_auto_20190118_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockingevent',
            name='month',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Month of stocking event as an integer'),
        ),
    ]
