# Generated by Django 2.2 on 2020-05-06 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_finclips_and_physchem_marks'),
        ('stocking', '0004_add_hatchery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockingevent',
            name='clipa',
        ),
        migrations.AddField(
            model_name='stockingevent',
            name='clip_efficiency',
            field=models.FloatField(blank=True, null=True, verbose_name='Clipping efficency as a percentage'),
        ),
        migrations.AddField(
            model_name='stockingevent',
            name='finclip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocking_events', to='common.FinClip'),
        ),
        migrations.AddField(
            model_name='stockingevent',
            name='fish_tags',
            field=models.ManyToManyField(to='common.FishTag'),
        ),
        migrations.AddField(
            model_name='stockingevent',
            name='hatchery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocking_events', to='stocking.Hatchery'),
        ),
        migrations.AddField(
            model_name='stockingevent',
            name='physchem_marks',
            field=models.ManyToManyField(to='common.PhysChemMark'),
        ),
    ]
