# Generated by Django 2.2 on 2020-05-08 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_renamed_finclip_to_compositefinclip'),
        ('stocking', '0005_new_data_upload_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hatchery',
            options={'verbose_name_plural': 'Hatcheries'},
        ),
        migrations.RenameField(
            model_name='stockingevent',
            old_name='finclip',
            new_name='clip_code',
        ),
        migrations.AlterUniqueTogether(
            name='hatchery',
            unique_together={('abbrev', 'hatchery_type', 'agency')},
        ),
    ]
