# Generated by Django 2.1.4 on 2019-02-05 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_auto_20190131_1916'),
        ('stocking', '0005_auto_20190131_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockingevent',
            name='jurisdiction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stocking_events', to='common.Jurisdiction'),
            preserve_default=False,
        ),
    ]
