# Generated by Django 2.2 on 2020-05-08 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_added_FinClip_and_m2m_to_event'),
        ('stocking', '0006_renamed_finclip_to_compositefinclip'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockingevent',
            name='fin_clips',
            field=models.ManyToManyField(to='common.FinClip'),
        ),
        migrations.AlterField(
            model_name='stockingevent',
            name='clip_code',
            field=models.ForeignKey(blank=True, help_text='Reported Composite Clip Code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocking_events', to='common.CompositeFinClip'),
        ),
        migrations.AlterUniqueTogether(
            name='hatchery',
            unique_together=set(),
        ),
    ]
