# Generated by Django 2.1.4 on 2019-02-06 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocking', '0006_stockingevent_jurisdiction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockingevent',
            name='lake',
        ),
        migrations.RemoveField(
            model_name='stockingevent',
            name='stateprov',
        ),
    ]
