# Generated by Django 2.2 on 2020-05-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocking', '0007_auto_20200508_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockingevent',
            name='stock_id',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='unique event identifier provided by agency'),
        ),
    ]
