# Generated by Django 2.2 on 2020-11-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocking', '0008_added_stock_id_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockingevent',
            name='fin_clips',
            field=models.ManyToManyField(related_name='stocking_events', to='common.FinClip'),
        ),
        migrations.AlterField(
            model_name='stockingevent',
            name='fish_tags',
            field=models.ManyToManyField(related_name='stocking_events', to='common.FishTag'),
        ),
        migrations.AlterField(
            model_name='stockingevent',
            name='marks',
            field=models.ManyToManyField(related_name='stocking_events', to='common.Mark'),
        ),
        migrations.AlterField(
            model_name='stockingevent',
            name='physchem_marks',
            field=models.ManyToManyField(related_name='stocking_events', to='common.PhysChemMark'),
        ),
        migrations.AlterField(
            model_name='stockingevent',
            name='tag_no',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='CWT numbers'),
        ),
        migrations.AlterField(
            model_name='stockingevent',
            name='tag_ret',
            field=models.FloatField(blank=True, null=True, verbose_name='CWT retention as a percentage'),
        ),
    ]
