# Generated by Django 2.2.17 on 2021-03-04 13:56

from django.db import migrations, models
import fsdviz.common.utils


def migrate__lat__lon_from_geom(apps, schema_editor):
    StockingEvent = apps.get_model("stocking", "StockingEvent")
    events = StockingEvent.objects.all()
    for event in events:
        event._dd_lat = event.geom.y
        event._dd_lon = event.geom.x
        event.save()


def unmigrate__lat__lon_from_geom(apps, schema_editor):
    StockingEvent = apps.get_model("stocking", "StockingEvent")
    events = StockingEvent.objects.all()
    for event in events:
        event._dd_lat = event.geom.y
        event._dd_lon = event.geom.x
        event.save()


class Migration(migrations.Migration):

    dependencies = [
        ("stocking", "0011_auto_20210218_1148"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockingevent",
            name="_dd_lat",
            field=models.FloatField(
                default=45.0,
                editable=False,
                verbose_name="Latitude in decimal degrees derived from geom",
            ),
        ),
        migrations.AddField(
            model_name="stockingevent",
            name="_dd_lon",
            field=models.FloatField(
                default=-81.0,
                editable=False,
                verbose_name="Longitude in decimal degrees derived from geom",
            ),
        ),
        migrations.AlterField(
            model_name="stockingevent",
            name="dd_lon",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Reported longitude in decimal degrees",
            ),
        ),
        migrations.AlterField(
            model_name="stockingevent",
            name="stock_id",
            field=models.CharField(
                db_index=True,
                default=fsdviz.common.utils.unique_string,
                max_length=100,
                unique=True,
            ),
        ),
        migrations.RunPython(
            migrate__lat__lon_from_geom, unmigrate__lat__lon_from_geom
        ),
    ]
