# Generated by Django 2.2.17 on 2021-03-19 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocking', '0012_calc__lat__lon_from_geom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockingevent',
            old_name='_dd_lat',
            new_name='geom_lat',
        ),
        migrations.RenameField(
            model_name='stockingevent',
            old_name='_dd_lon',
            new_name='geom_lon',
        ),
    ]
