# Generated by Django 2.2.19 on 2021-05-10 15:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_sequence_lower_upper'),
        ('stocking', '0013_renamed__dd_latlong_to_geom_latlon'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlingEquivalent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yreq_factor', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('comment', models.CharField(max_length=1000)),
                ('lifestage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yealing_equivalents', to='stocking.LifeStage')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yealing_equivalents', to='common.Species')),
            ],
            options={
                'unique_together': {('species', 'lifestage')},
            },
        ),
    ]
