# Generated by Django 2.2.19 on 2021-05-29 19:26

from django.db import migrations, models
import django.db.models.deletion
import fsdviz.stocking.models


class Migration(migrations.Migration):

    dependencies = [
        ('stocking', '0015_edit_yreq_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockingevent',
            name='condition',
            field=models.ForeignKey(default=fsdviz.stocking.models.get_default_condition, on_delete=django.db.models.deletion.CASCADE, related_name='stocking_events', to='stocking.Condition'),
        ),
        migrations.AlterField(
            model_name='stockingevent',
            name='fish_tags',
            field=models.ManyToManyField(blank=True, related_name='stocking_events', to='common.FishTag'),
        ),
        migrations.AlterField(
            model_name='stockingevent',
            name='marks',
            field=models.ManyToManyField(blank=True, related_name='stocking_events', to='common.Mark'),
        ),
        migrations.AlterField(
            model_name='stockingevent',
            name='physchem_marks',
            field=models.ManyToManyField(blank=True, related_name='stocking_events', to='common.PhysChemMark'),
        ),
        migrations.AlterField(
            model_name='stockingevent',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='weight of stocked fish in grams'),
        ),
    ]
