# Generated by Django 2.2.24 on 2021-09-13 15:58

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocking", "0016_stocking_event_fk_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="lifestage",
            name="color",
            field=colorfield.fields.ColorField(default="#FF0000", max_length=18),
        ),
        migrations.AddField(
            model_name="stockingmethod",
            name="color",
            field=colorfield.fields.ColorField(default="#FF0000", max_length=18),
        ),
    ]
