# Generated by Django 2.2.24 on 2021-09-13 16:03

from django.db import migrations

colors_list = [
    "#3cb44b",
    "#4363d8",
    "#e6194b",
    "#f58231",
    "#46f0f0",
    "#ffe119",
    "#f032e6",
    "#911eb4",
    "#bcf60c",
    "#fabebe",
    "#008080",
    "#e6beff",
    "#9a6324",
    "#fffac8",
    "#800000",
    "#aaffc3",
    "#808000",
    "#ffd8b1",
    "#000075",
    "#808080",
    "#ffffff",
]


def fill_colorfields(apps, schema_editor):

    LifeStage = apps.get_model("stocking", "LifeStage")
    StockingMethod = apps.get_model("stocking", "StockingMethod")

    for model in [LifeStage, StockingMethod]:
        for i, item in enumerate(model.objects.all()):
            item.color = colors_list[i]
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ("stocking", "0017_stocking_colorfields"),
    ]

    operations = [
        migrations.RunPython(fill_colorfields, reverse_code=migrations.RunPython.noop)
    ]
