# Generated by Django 2.2.24 on 2021-12-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocking', '0019_cwt_reuse_sql_triggers'),
    ]

    operations = [
        migrations.AddField(
            model_name='hatchery',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
