# Generated by Django 2.2.24 on 2021-12-03 18:08

from django.db import migrations
from django.db.models import Max


def forwards(apps, schema_editor):
    Hatchery = apps.get_model("stocking", "Hatchery")

    hatchery_ids = (
        Hatchery.objects.annotate(latest_year=Max("stocking_events__year"))
        .filter(latest_year__lte=2000)
        .values_list("id")
    )
    Hatchery.objects.filter(pk__in=hatchery_ids).update(active=False)


def backwards(apps, schema_editor):

    Hatchery = apps.get_model("stocking", "Hatchery")
    Hatchery.objects.update(active=True)


class Migration(migrations.Migration):

    dependencies = [
        ("stocking", "0020_hatchery_active_flag"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
