# Generated by Django 2.2.28 on 2022-05-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocking', '0022_data_upload_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockingevent',
            name='tag_no',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='CWT numbers'),
        ),
    ]
