# Generated by Django 2.2.28 on 2022-05-16 13:41

from django.db import migrations


class Migration(migrations.Migration):
    """Update the tag_no field in the stocking event model with a string
    that is formed by concatenating the assocaiated cwt numbers
    seperated by semi-colons.
    """

    dependencies = [
        ("stocking", "0023_increase_tag_no_to_150_characters"),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE stocking_stockingevent
               SET tag_no = subquery.tag_no
            FROM (SELECT stock_id,
                         STRING_AGG(cwt_number,';') AS tag_no
                  FROM stocking_stockingevent AS events
                    JOIN common_cwtsequence_events ON events.id = common_cwtsequence_events.stockingevent_id
                    JOIN common_cwtsequence ON common_cwtsequence.id = common_cwtsequence_events.cwtsequence_id
                    JOIN common_cwt AS cwt ON cwt.id = common_cwtsequence.cwt_id
                  WHERE cwt_number <> '999'
                  GROUP BY stock_id) AS subquery
            WHERE stocking_stockingevent.stock_id = subquery.stock_id;
            """,
            None,
        ),
    ]
