# Generated by Django 2.2.28 on 2022-09-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocking', '0024_update_tag_no_with_tag_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockingevent',
            name='notes',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
