# Generated by Django 4.2.11 on 2024-04-03 19:20

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocking", "0026_add_timestamped_base_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datauploadevent",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="hatchery",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="lifestage",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FF0000", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AlterField(
            model_name="lifestage",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="stockingevent",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="stockingmethod",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FF0000", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AlterField(
            model_name="stockingmethod",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="yearlingequivalent",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
