# Generated by Django 4.2.11 on 2024-04-25 19:57

from django.db import migrations, models
import django.db.models.deletion
import fsdviz.stocking.models


class Migration(migrations.Migration):

    dependencies = [
        ("stocking", "0028_alter_condition_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Condition",
            new_name="StockingMortality",
        ),
        migrations.AlterModelOptions(
            name="stockingmortality",
            options={"ordering": ["value"]},
        ),
        migrations.RenameField(
            model_name="stockingmortality",
            old_name="condition",
            new_name="value",
        ),
        migrations.RenameField(
            model_name="stockingevent",
            old_name="condition",
            new_name="stocking_mortality",
        ),


    ]
