# Generated by Django 4.2.11 on 2024-04-03 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("recovery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recovery",
            name="created_timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recovery",
            name="modified_timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="recoveryevent",
            name="created_timestamp",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recoveryevent",
            name="modified_timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="recovery",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="recoveryevent",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
