# Generated by Django 2.1.4 on 2019-01-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_remove_cwt_agency'),
        ('recovery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recovery',
            name='marks',
            field=models.ManyToManyField(to='common.Mark'),
        ),
        migrations.AddField(
            model_name='recovery',
            name='weight_form',
            field=models.CharField(blank=True, choices=[('R', 'Round'), ('D', 'Dressed'), ('U', 'Unknown')], default='U', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='maturity',
            field=models.CharField(blank=True, choices=[('I', 'Immature'), ('M', 'Mature'), ('U', 'Unknown'), ('G', 'Gravid'), ('S', 'Spent'), ('R', 'Ripe')], default='U', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='recoveryevent',
            name='net_material',
            field=models.CharField(blank=True, choices=[('M', 'Monofilament'), ('N', 'Nylon'), ('O', 'Other'), ('U', 'Unknown')], max_length=2, null=True),
        ),
    ]
