# Generated by Django 2.1.4 on 2018-12-13 21:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbrev', models.CharField(max_length=15, unique=True)),
                ('agency_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuildDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_date', models.DateField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Grid10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid', models.CharField(max_length=4)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Lake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbrev', models.CharField(max_length=2, unique=True)),
                ('lake_name', models.CharField(max_length=30, unique=True)),
                ('shoreline', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='ManagementUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=25)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('mu_type', models.CharField(choices=[('mu', 'Management Unit'), ('ltrz', 'Lake Trout Rehabilitation Zone'), ('qma', 'Quota Management Area'), ('aa', 'Assessment Area'), ('stat_dist', 'Statistical District')], default='mu', max_length=10)),
                ('lake', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.Lake')),
            ],
            options={
                'ordering': ['mu_type', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Readme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(editable=False)),
                ('comment', models.TextField()),
                ('initials', models.CharField(max_length=4)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbrev', models.CharField(max_length=5, unique=True)),
                ('common_name', models.CharField(max_length=50, unique=True)),
                ('speciescommon', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=50, null=True)),
                ('species_code', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Species',
            },
        ),
        migrations.CreateModel(
            name='StateProvince',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbrev', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('country', models.CharField(choices=[('USA', 'U.S.A.'), ('CAN', 'Canada')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strain_code', models.CharField(max_length=10)),
                ('strain_label', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('strain_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Species')),
            ],
        ),
        migrations.CreateModel(
            name='StrainRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_strain', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rawstrain', to='common.Species')),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rawstrain', to='common.Strain')),
            ],
        ),
        migrations.AddField(
            model_name='species',
            name='strains',
            field=models.ManyToManyField(related_name='species', through='common.StrainRaw', to='common.Strain'),
        ),
        migrations.AddField(
            model_name='grid10',
            name='lake',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.Lake'),
        ),
        migrations.AlterUniqueTogether(
            name='strainraw',
            unique_together={('species', 'strain', 'raw_strain')},
        ),
    ]
