# Generated by Django 2.1.4 on 2018-12-14 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ['abbrev'], 'verbose_name_plural': 'Agencies'},
        ),
        migrations.AlterModelOptions(
            name='grid10',
            options={'ordering': ['lake__abbrev', 'grid']},
        ),
        migrations.AlterModelOptions(
            name='lake',
            options={'ordering': ['abbrev']},
        ),
        migrations.AlterModelOptions(
            name='managementunit',
            options={'ordering': ['lake__abbrev', 'mu_type', 'label']},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['abbrev'], 'verbose_name_plural': 'Species'},
        ),
        migrations.AlterModelOptions(
            name='stateprovince',
            options={'ordering': ['abbrev']},
        ),
        migrations.AlterModelOptions(
            name='strain',
            options={'ordering': ['species__abbrev', 'strain_code']},
        ),
        migrations.AlterModelOptions(
            name='strainraw',
            options={'ordering': ['species__abbrev', 'raw_strain']},
        ),
        migrations.AlterUniqueTogether(
            name='strain',
            unique_together={('strain_species', 'strain_code')},
        ),
    ]
