# Generated by Django 2.2 on 2019-08-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('stocking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cwtsequence',
            name='events',
            field=models.ManyToManyField(related_name='cwt_series', to='stocking.StockingEvent'),
        ),
        migrations.AlterUniqueTogether(
            name='cwt',
            unique_together={('cwt_number', 'manufacturer')},
        ),
        migrations.AlterUniqueTogether(
            name='strainraw',
            unique_together={('species', 'strain', 'raw_strain')},
        ),
        migrations.AlterUniqueTogether(
            name='strain',
            unique_together={('strain_species', 'strain_code')},
        ),
    ]
