# Generated by Django 2.1.4 on 2019-01-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20181214_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatLonFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip_code', models.CharField(max_length=2)),
                ('mark_code', models.CharField(max_length=4, unique=True)),
                ('mark_type', models.CharField(choices=[('chemical', 'Chemical'), ('finclip', 'Fin Clip'), ('tag', 'Tag')], default='finclip', max_length=8)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['mark_code'],
            },
        ),
    ]
