# Generated by Django 2.2 on 2019-09-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_cwt_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cwt',
            name='slug',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
