# Generated by Django 2.2 on 2019-04-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_grid10_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid10',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
