# Generated by Django 2.1.4 on 2019-01-08 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_latlonflag_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='CWT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cwt_number', models.CharField(max_length=6)),
                ('tag_type', models.CharField(choices=[('cwt', 'Coded Wire Tag'), ('sequential', 'Sequential Coded Wire Tag')], default='cwt', max_length=10)),
                ('manufacturer', models.CharField(choices=[('mm', 'Micro Mark'), ('nmt', 'Northwest Marine Technology')], default='nmt', max_length=10)),
                ('tag_count', models.IntegerField()),
                ('tag_reused', models.BooleanField(db_index=True, default=False)),
                ('multiple_species', models.BooleanField(db_index=True, default=False)),
                ('multiple_strains', models.BooleanField(db_index=True, default=False)),
                ('multiple_yearclasses', models.BooleanField(db_index=True, default=False)),
                ('multiple_makers', models.BooleanField(db_index=True, default=False)),
                ('multiple_agencies', models.BooleanField(db_index=True, default=False)),
                ('multiple_lakes', models.BooleanField(db_index=True, default=False)),
                ('multiple_grid10s', models.BooleanField(db_index=True, default=False)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cwts', to='common.Agency')),
            ],
            options={
                'ordering': ['cwt_number'],
            },
        ),
        migrations.CreateModel(
            name='CWTsequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_start', models.IntegerField(default=1)),
                ('seq_end', models.IntegerField(default=1)),
                ('cwt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cwt_series', to='common.CWT')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cwt',
            unique_together={('cwt_number', 'manufacturer')},
        ),
    ]
