# Generated by Django 2.2 on 2019-09-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("common", "0004_auto_20190923_1649")]

    operations = [
        migrations.AddField(
            model_name="strain",
            name="slug",
            field=models.CharField(max_length=20, null=True, unique=True),
        )
    ]
