# Generated by Django 2.1.4 on 2019-01-09 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20190108_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mark',
            options={'ordering': ['mark_type', 'mark_code']},
        ),
    ]
