# Generated by Django 2.2 on 2019-09-24 20:33
from django.utils.text import slugify
from django.db import migrations


class Migration(migrations.Migration):
    def forwards_func(apps, schema_editor):
        Strain = apps.get_model("common", "Strain")
        for instance in Strain.objects.all():
            if not instance.slug:
                strain_code = instance.strain_code
                species = instance.strain_species.abbrev
                slug = "{}-{}".format(species, strain_code)
                instance.slug = slugify(slug)
                instance.save()

    def reverse_func(apps, schema_editor):
        pass

    dependencies = [("common", "0005_strain_slug")]

    operations = [migrations.RunPython(forwards_func, reverse_func)]
