# Generated by Django 2.2 on 2019-09-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("common", "0006_auto_20190924_1633")]

    operations = [
        migrations.AlterField(
            model_name="strain",
            name="slug",
            field=models.CharField(max_length=20, unique=True),
        )
    ]
