# Generated by Django 2.1.4 on 2019-01-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocking', '0004_auto_20190118_1425'),
        ('common', '0006_auto_20190109_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='cwtsequence',
            name='events',
            field=models.ManyToManyField(related_name='cwt_series', to='stocking.StockingEvent'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='mark_type',
            field=models.CharField(choices=[('chemical', 'Chemical'), ('finclip', 'Fin Clip'), ('tag', 'Tag'), ('unknown', 'Unknown')], default='finclip', max_length=8),
        ),
    ]
