# Generated by Django 2.1.4 on 2019-01-18 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20190118_1425'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cwt',
            unique_together={('cwt_number', 'manufacturer', 'agency')},
        ),
    ]
