# Generated by Django 2.1.4 on 2019-01-23 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20190118_1543'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cwt',
            unique_together={('cwt_number', 'manufacturer')},
        ),
    ]
