# Generated by Django 2.2 on 2019-10-04 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20191004_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grid10',
            name='centroid',
        ),
    ]
