# Generated by Django 2.2 on 2019-10-07 14:29

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_remove_grid10_centroid'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid10',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
