# Generated by Django 2.2 on 2019-10-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_grid10_centroid'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementunit',
            name='grid10s',
            field=models.ManyToManyField(to='common.Grid10'),
        ),
    ]
