# Generated by Django 2.2 on 2020-05-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_managementunit_grid10s'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinClip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip_code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['clip_code'],
            },
        ),
        migrations.CreateModel(
            name='PhysChemMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_code', models.CharField(max_length=10, unique=True)),
                ('mark_type', models.CharField(choices=[('thermal', 'Thermal'), ('chemcial', 'Chemical'), ('dye', 'Dye'), ('physical', 'physical'), ('unknown', 'Unknown')], max_length=10)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['mark_code'],
            },
        ),
        migrations.CreateModel(
            name='FishTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_code', models.CharField(max_length=10, unique=True)),
                ('tag_type', models.CharField(choices=[('floy', 'Floy'), ('carlin', 'Carlin'), ('jaw', 'Jaw'), ('cwt', 'CWT'), ('dart', 'Dart'), ('pit', 'PIT'), ('unknown', 'Unknown')], max_length=10)),
                ('tag_colour', models.CharField(choices=[('unknown', 'Unknown'), ('white', 'White'), ('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue')], max_length=10)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['tag_code'],
                'unique_together': {('tag_colour', 'tag_type')},
            },
        ),
    ]
