# Generated by Django 2.2 on 2020-05-08 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocking', '0005_new_data_upload_fields'),
        ('common', '0012_finclips_and_physchem_marks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinClip',
            new_name='CompositeFinClip',
        ),
    ]
