# Generated by Django 2.2 on 2020-05-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_renamed_finclip_to_compositefinclip'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinClip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbrev', models.CharField(max_length=2, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
