# Generated by Django 2.2 on 2020-08-06 19:16

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_cwt_sequence_range_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cwtsequence',
            options={'ordering': ['cwt__cwt_number', 'sequence']},
        ),
        migrations.RemoveField(
            model_name='cwtsequence',
            name='seq_end',
        ),
        migrations.RemoveField(
            model_name='cwtsequence',
            name='seq_start',
        ),
        migrations.AlterField(
            model_name='cwtsequence',
            name='sequence',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(default=(0, 0)),
        ),
    ]
