# Generated by Django 2.2 on 2020-11-13 21:08

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import fsdviz.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_removed_seq_start_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementunit',
            name='jurisdiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Jurisdiction'),
        ),
        migrations.AlterField(
            model_name='cwtsequence',
            name='sequence',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(default=(0, 0), validators=[fsdviz.common.validators.validate_cwt_sequence_range]),
        ),
    ]
