# Generated by Django 2.2.17 on 2021-03-03 22:28

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import fsdviz.common.validators

from psycopg2.extras import NumericRange


def migrate_sequence_bounds(apps, schema_editor):
    CWTsequence = apps.get_model("common", "CWTsequence")
    records = CWTsequence.objects.filter(sequence__gt=NumericRange(0, 1))
    for record in records:
        record.seq_lower = record.sequence.lower
        record.seq_upper = record.sequence.upper
        record.save()


def unmigrate_sequence_bounds(apps, schema_editor):
    CWTsequence = apps.get_model("common", "CWTsequence")
    records = CWTsequence.objects.filter(sequence__gt=NumericRange(0, 1))
    for record in records:
        record.seq_lower = 0
        record.seq_upper = 1
        record.save()


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0018_management_unit_fk_to_jurisdiction"),
    ]

    operations = [
        migrations.AddField(
            model_name="cwtsequence",
            name="seq_lower",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="cwtsequence",
            name="seq_upper",
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name="cwtsequence",
            name="sequence",
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(
                default=(0, 1),
                validators=[fsdviz.common.validators.validate_cwt_sequence_range],
            ),
        ),
        migrations.RunPython(migrate_sequence_bounds, unmigrate_sequence_bounds),
    ]
