# Generated by Django 2.2.24 on 2021-12-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_fill_colorfields'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='strain',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='strainraw',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
