# Generated by Django 2.2.24 on 2021-12-03 16:36

from django.db import migrations
from django.db.models import Max


def forwards(apps, schema_editor):
    Species = apps.get_model("common", "Species")
    StrainRaw = apps.get_model("common", "StrainRaw")
    Strain = apps.get_model("common", "Strain")

    species_ids = (
        Species.objects.annotate(latest_year=Max("stocking_events__year"))
        .filter(latest_year__lte=2000)
        .values_list("id")
    )
    Species.objects.filter(pk__in=species_ids).update(active=False)

    strain_ids = (
        Strain.objects.annotate(latest_year=Max("species__stocking_events__year"))
        .filter(latest_year__lte=2000)
        .values_list("id")
    )
    Strain.objects.filter(pk__in=strain_ids).update(active=False)

    strainraw_ids = (
        StrainRaw.objects.annotate(latest_year=Max("stocking_events__year"))
        .filter(latest_year__lte=2000)
        .values_list("id")
    )
    StrainRaw.objects.filter(pk__in=strainraw_ids).update(active=False)


def backwards(apps, schema_editor):

    Species = apps.get_model("common", "Species")
    StrainRaw = apps.get_model("common", "StrainRaw")
    Strain = apps.get_model("common", "Strain")

    Species.objects.update(active=True)
    Strain.objects.update(active=True)
    StrainRaw.objects.update(active=True)


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0022_species_strain_active_flag"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
