# Generated by Django 2.2.28 on 2022-06-06 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_set_species_strain_active_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='lake',
            name='max_lat',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(41.3), django.core.validators.MaxValueValidator(49.1)], verbose_name='Maximum latitude for events in this lake'),
        ),
        migrations.AddField(
            model_name='lake',
            name='max_lon',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-92.4), django.core.validators.MaxValueValidator(-74.3)], verbose_name='Maximum longitude for events in this lake'),
        ),
        migrations.AddField(
            model_name='lake',
            name='min_lat',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(41.3), django.core.validators.MaxValueValidator(49.1)], verbose_name='Minimum latitude for events in this lake'),
        ),
        migrations.AddField(
            model_name='lake',
            name='min_lon',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-92.4), django.core.validators.MaxValueValidator(-74.3)], verbose_name='Minimum longitude for events in this lake'),
        ),
    ]
