# Generated by Django 2.2.28 on 2022-06-06 20:34


from django.db import migrations
from django.contrib.gis.db.models import Extent


def populate_extents(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.

    Lake = apps.get_model("common", "Lake")
    StockingEvent = apps.get_model("stocking", "StockingEvent")
    for lake in Lake.objects.all():
        bounds = StockingEvent.objects.filter(jurisdiction__lake=lake).aggregate(
            Extent("geom")
        )["geom__extent"]
        lake.max_lat = bounds[3]
        lake.min_lat = bounds[1]
        lake.max_lon = bounds[2]
        lake.min_lon = bounds[0]
        lake.save()


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0024_add_bounding_fields_to_lakes"),
    ]

    operations = [
        migrations.RunPython(populate_extents),
    ]
