# Generated by Django 2.2.28 on 2023-06-07 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_populate_lake_extents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lake',
            name='max_lat',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(41.3), django.core.validators.MaxValueValidator(49.1)], verbose_name='Northern-most latitude for events in this lake'),
        ),
        migrations.AlterField(
            model_name='lake',
            name='max_lon',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-92.4), django.core.validators.MaxValueValidator(-74.3)], verbose_name='Eastern-most longitude for events in this lake'),
        ),
        migrations.AlterField(
            model_name='lake',
            name='min_lat',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(41.3), django.core.validators.MaxValueValidator(49.1)], verbose_name='Southern-most latitude for events in this lake'),
        ),
        migrations.AlterField(
            model_name='lake',
            name='min_lon',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-92.4), django.core.validators.MaxValueValidator(-74.3)], verbose_name='Western-most longitude for events in this lake'),
        ),
    ]
