# Generated by Django 2.2.28 on 2023-06-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_add_timestamped_base_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('file', models.ImageField(upload_to='uploaded_images')),
            ],
        ),
    ]
