# Generated by Django 4.2.11 on 2024-08-19 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0029_add_autofield_primary_key"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BuildDate",
        ),
        migrations.DeleteModel(
            name="Readme",
        ),
    ]
