# Generated by Django 4.2.11 on 2024-08-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0030_drop_readme_builddate_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="LookupDescription",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("modified_timestamp", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.CharField(
                        editable=False,
                        help_text="Reference this string in the template.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("model_name", models.CharField(max_length=255, unique=True)),
                (
                    "description",
                    models.TextField(
                        default="Coming Soon....",
                        help_text="Lookup Table Description (markdown).",
                    ),
                ),
                (
                    "description_html",
                    models.TextField(
                        editable=False, help_text="Lookup Table Description (html)."
                    ),
                ),
            ],
            options={
                "ordering": ["model_name"],
            },
        ),
    ]
