# Generated by Django 4.2.11 on 2024-08-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocking", "0030_rename_stocking_event_strain_raw_to_alias"),
        ("common", "0031_create_table_lookup_description"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StrainRaw",
            new_name="StrainAlias",
        ),
        migrations.AlterField(
            model_name="lookupdescription",
            name="model_name",
            field=models.CharField(
                help_text="Plural Name of Model Instances (e.g. - Lakes). This usually matches the heading in the Lookup Tables html template.",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="lookupdescription",
            name="slug",
            field=models.CharField(
                editable=False,
                help_text="This is the string referenced in the template for this model.",
                max_length=255,
                unique=True,
            ),
        ),


        # changes fk reference on stocking event from strain_raw_id to strain_alias_id
        migrations.RunSQL(
            """

        CREATE OR REPLACE FUNCTION update_reused_cwt_flags_trigger_fct () RETURNS TRIGGER LANGUAGE PLPGSQL
        AS
' BEGIN


UPDATE common_cwt
   SET multiple_makers = CASE
                           WHEN cwt_number IN (SELECT DISTINCT mm.cwt_number
                                               FROM (SELECT DISTINCT cwt_number,
                                                            manufacturer
                                                     FROM common_cwt
                                                     WHERE manufacturer = ''mm'') AS mm
                                                 JOIN common_cwt AS cwt ON cwt.cwt_number = mm.cwt_number
                                               WHERE cwt.manufacturer = ''nmt'') THEN TRUE
                           ELSE FALSE
                         END,
       multiple_strains = CASE
                            WHEN cwt_number IN (SELECT cwt_number
                                                --,      common_name,
                                                --       COUNT(strain_label) AS strains
                                                FROM (SELECT DISTINCT cwt_number,
                                                             species.common_name,
                                                             strain.strain_label
                                                      FROM stocking_stockingevent AS event
                                                        JOIN common_cwtsequence_events ON common_cwtsequence_events.stockingevent_id = event.id
                                                        JOIN common_cwtsequence ON common_cwtsequence_events.cwtsequence_id = common_cwtsequence.id
                                                        JOIN common_cwt AS cwt ON cwt.id = common_cwtsequence.cwt_id
                                                        JOIN common_species AS species ON species.id = event.species_id
                                                        JOIN common_strainalias AS strainalias ON strainalias.id = event.strain_alias_id
                                                        JOIN common_strain AS strain ON strain.id = strainalias.strain_id) AS tmp
                                                GROUP BY cwt_number,
                                                         common_name
                                                HAVING COUNT(cwt_number) > 1) THEN TRUE
                            ELSE FALSE
                          END,
       multiple_agencies = CASE
                             WHEN cwt_number IN (SELECT cwt_number
                                                 --       ,COUNT(agency_id) AS Agencies
                                                 FROM (SELECT DISTINCT cwt_number,
                                                              events.agency_id
                                                       FROM stocking_stockingevent AS events
                                                         JOIN common_cwtsequence_events ON common_cwtsequence_events.stockingevent_id = events.id
                                                         JOIN common_cwtsequence ON common_cwtsequence_events.cwtsequence_id = common_cwtsequence.id
                                                         JOIN common_cwt AS cwt ON cwt.id = common_cwtsequence.cwt_id) AS tmp
                                                 GROUP BY cwt_number
                                                 HAVING COUNT(cwt_number) > 1) THEN TRUE
                             ELSE FALSE
                           END,
       multiple_species = CASE
                            WHEN cwt_number IN (SELECT cwt_number
                                                --,COUNT(species_id) AS Species
                                                FROM (SELECT DISTINCT cwt_number,
                                                             events.species_id
                                                      FROM stocking_stockingevent AS events
                                                        JOIN common_cwtsequence_events ON common_cwtsequence_events.stockingevent_id = events.id
                                                        JOIN common_cwtsequence ON common_cwtsequence_events.cwtsequence_id = common_cwtsequence.id
                                                        JOIN common_cwt AS cwt ON cwt.id = common_cwtsequence.cwt_id) AS tmp
                                                GROUP BY cwt_number
                                                HAVING COUNT(species_id) > 1) THEN TRUE
                            ELSE FALSE
                          END,
       multiple_lakes = CASE
                          WHEN cwt_number IN (SELECT cwt_number
                                              --,COUNT(lake_id) AS Lakesb
                                              FROM (SELECT DISTINCT cwt_number,
                                                           jurisdiction.lake_id
                                                    FROM stocking_stockingevent AS events
                                                      JOIN common_jurisdiction AS jurisdiction ON jurisdiction.id = events.jurisdiction_id
                                                      JOIN common_cwtsequence_events ON common_cwtsequence_events.stockingevent_id = events.id
                                                      JOIN common_cwtsequence ON common_cwtsequence_events.cwtsequence_id = common_cwtsequence.id
                                                      JOIN common_cwt AS cwt ON cwt.id = common_cwtsequence.cwt_id) AS tmp
                                              GROUP BY cwt_number
                                              HAVING COUNT(lake_id) > 1) THEN TRUE
                          ELSE FALSE
                        END,
       multiple_yearclasses = CASE
                                WHEN cwt_number IN (SELECT cwt_number
                                                    --       ,COUNT(year_class) AS YearClasses
                                                    FROM (SELECT DISTINCT cwt_number,
                                                                 events.species_id,
                                                                 events.year_class
                                                          FROM stocking_stockingevent AS events
                                                            JOIN common_cwtsequence_events ON common_cwtsequence_events.stockingevent_id = events.id
                                                            JOIN common_cwtsequence ON common_cwtsequence_events.cwtsequence_id = common_cwtsequence.id
                                                            JOIN common_cwt AS cwt ON cwt.id = common_cwtsequence.cwt_id) AS tmp
                                                    GROUP BY cwt_number,
                                                             species_id
                                                    HAVING COUNT(cwt_number) > 1) THEN TRUE
                                ELSE FALSE
                              END;

UPDATE common_cwt
   SET tag_reused = case when
   cwt_number IN (SELECT distinct cwt_number
                     FROM common_cwt
                     WHERE multiple_species = TRUE
                     OR    multiple_strains = TRUE
                     OR    multiple_yearclasses = TRUE
                     OR    multiple_makers = TRUE
                     OR    multiple_agencies = TRUE
                     OR    multiple_lakes = TRUE)
                     THEN TRUE
                           ELSE FALSE
                         END;
return NEW;
END;
';

DROP TRIGGER update_reused_cwt_flags_trigger on stocking_stockingevent;

CREATE TRIGGER update_reused_cwt_flags_trigger
AFTER INSERT OR UPDATE OR DELETE ON stocking_stockingevent
FOR EACH STATEMENT
EXECUTE PROCEDURE update_reused_cwt_flags_trigger_fct();
""",
            """
            """,
        )




    ]
