# Generated by Django 4.2.11 on 2024-08-20 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0032_rename_table_strainraw_to_strainalias"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="strainalias",
            options={
                "ordering": ["species__abbrev", "strain_alias"],
                "verbose_name_plural": "Strain Aliases",
            },
        ),
        migrations.RenameField(
            model_name="strainalias",
            old_name="raw_strain",
            new_name="strain_alias",
        ),
        migrations.AlterUniqueTogether(
            name="strainalias",
            unique_together={("species", "strain", "strain_alias")},
        ),
    ]
