# Generated by Django 4.2.11 on 2024-08-20 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0033_rename_strainraw_fld_to_strain_alias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strain",
            name="strain_code",
            field=models.CharField(
                max_length=10,
                verbose_name="Nominal Strain Code for groups of strain alias values",
            ),
        ),
        migrations.AlterField(
            model_name="strainalias",
            name="species",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="strain_aliases",
                to="common.species",
            ),
        ),
        migrations.AlterField(
            model_name="strainalias",
            name="strain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="strain_aliases",
                to="common.strain",
            ),
        ),
        migrations.AlterField(
            model_name="strainalias",
            name="strain_alias",
            field=models.CharField(
                max_length=100, verbose_name="Submitted strain alias code"
            ),
        ),
    ]
