# Generated by Django 2.2 on 2020-11-17 16:00

from django.db import migrations, models
import django.db.models.deletion
import fsdviz.myusers.models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0018_management_unit_fk_to_jurisdiction"),
        ("myusers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="agency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.Agency",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="lakes",
            field=models.ManyToManyField(to="common.Lake"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("glsc", "Great Lakes Stocking Coordinator"),
                    ("am", "Agency Manager"),
                    ("asc", "Agency Stocking Coordinator"),
                    ("au", "Agency User"),
                ],
                default="au",
                max_length=4,
            ),
        ),
    ]
