# Generated by Django 2.2 on 2020-11-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myusers', '0002_user_role_agency_lakes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='fake_email@fake.com', max_length=254, unique=True, verbose_name='Email address'),
            preserve_default=False,
        ),
    ]
