# Generated by Django 4.2.11 on 2024-04-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myusers", "0003_auto_20201118_1405"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
    ]
